### ISSUE TITLE
Issue with dot in project name when building project w. grunt

### ISSUE THREAD

**Issue by nottinhill** [mercadolibre/lazy.js#4]
When we are building our project a few dependencies require lazy.js and link it, the we see in CLI this error:

    Warning: Unable to read dist/public/bower_components/lazy.js

We strongly assume this is due to the dot in the name. Has anybody figured out how to get this to run with grunt?

**Comment by llinares** [comment]
@nottinhill **lazy.js** is deprecated. Now it's **aload**:

https://www.npmjs.com/package/aload
https://github.com/pazguille/aload

We will comunicate on this repo. Sorry if we didn't.
